Update setup
version codename variable debian

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1549,23 +1549,12 @@ do
 		echo "Please wait ..."
 		echo " "
 
-		if [ `pveversion | grep "pve-manager/[7]" | wc -l` -ne 1 ]
-		then
-			echo "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
-			apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
-			if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
-			echo "Promox VE NO Subscription repository has been successfully added."	
-			exit
-		fi
-
-		if [ `pveversion | grep "pve-manager/[8]" | wc -l` -ne 1 ]
-		then
-			echo "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
-			apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
-			if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
-			echo "Promox VE NO Subscription repository has been successfully added."	
-			exit
-		fi
+		. /etc/os-release
+		echo "deb http://download.proxmox.com/debian/pve $VERSION_CODENAME pve-no-subscription" > /etc/apt/sources.list.d/pxve-no-sub.list
+		apt update -y >> ${LOGFILE} 2>> ${LOGFILE}
+		if [ $? -ne 0 ]; then echo "apt update error - check log file ${LOGFILE}"; exit; fi;
+		echo "Promox VE NO Subscription repository has been successfully added."	
+		exit
 
 	fi
 
